language: node_js
node_js:
  - 10

services:
  - docker

before_install:
  - docker build -t kuantse/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kuantse/react-test npm run test

after_success:
  - docker build -t kuantse/multi-client ./client
  - docker build -t kuantse/multi-nginx ./nginx
  - docker build -t kuantse/multi-server ./server
  - docker build -t kuantse/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kuantse/multi-client
  - docker push kuantse/multi-nginx
  - docker push kuantse/multi-server
  - docker push kuantse/multi-worker
